name: Test Miniconda Environment Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-windows:
    runs-on: windows-latest
    timeout-minutes: 15  # Increased timeout
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Windows Setup Script
        shell: cmd
        run: setup_and_run.bat simple
        
      - name: Remove Python Environment
        run: conda env remove -n pydrone_balloon_log_analyze

      - name: Verify Python Environment
        shell: cmd
        run: setup_and_run.bat simple

      # - name: Verify Python main.py
      #   shell: cmd
      #   run: setup_and_run.bat

  test-macos:
    # GitHub Actions doesn't have Apple Silicon runners yet,
    # but we can still test the script's architecture detection logic
    runs-on: ${{matrix.os}}
    timeout-minutes: 15  # Increased timeout

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]

    steps:
      - uses: actions/checkout@v3
      
      - name: Make Script Executable
        run: chmod +x setup_and_run.sh
        
      - name: Run macOS Setup Script
        # Use proper execution method to avoid conda environment parsing issues
        run: bash ./setup_and_run.sh simple
          
      - name: Remove Python Environment
        run: conda env remove -n pydrone_balloon_log_analyze

      - name: Verify Python Environment
        run: bash ./setup_and_run.sh simple

      # - name: Verify Python main.py
      #   run: bash ./setup_and_run.sh

