name: Test Miniconda Environment Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Windows Setup Script
        shell: cmd
        run: setup_and_run.bat
        
      - name: Verify Python Environment
        shell: cmd
        run: |
          call %USERPROFILE%\miniconda3\Scripts\activate.bat py311
          python -c "import sys; print(f'Python {sys.version}')"
          python -c "import numpy; print(f'NumPy {numpy.__version__}')"
          python -c "import pandas; print(f'Pandas {pandas.__version__}')"

  test-macos:
    # GitHub Actions doesn't have Apple Silicon runners yet,
    # but we can still test the script's architecture detection logic
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [macos-latest, macos-11, macos-12, macos-13]

    steps:
      - uses: actions/checkout@v3
      
      - name: Make Script Executable
        run: chmod +x setup_and_run.sh
        
      - name: Run macOS Setup Script
        run: ./setup_and_run.sh
        
      - name: Verify Python Environment
        run: |
          source $HOME/miniconda3/bin/activate py311
          python -c "import sys; print(f'Python {sys.version}')"
          python -c "import numpy; print(f'NumPy {numpy.__version__}')"
          python -c "import pandas; print(f'Pandas {pandas.__version__}')"